### PR TITLE
Update for KSP 1.7.x

### PR DESCRIPTION
**Pull request by siimav**
Works with KSP versions starting from 1.4.0.

### CODE REVIEW

**Comment by raidernick** [comment]
Can somebody else test to to confirm that it's actually working. I tried it in ksp 1.3.1 and I'm getting floppy noodle rockets.
@pap1723

**Comment by siimav** [comment]
After the latest Starwaster's changes it no longer even builds on KSP 1.3.1. I used KSP 1.4.5 for putting the updated dll together.
@pap1723 Please drop that into your 1.6 install the next time you fire it up.

**Comment by PhineasFreak** [comment]
If the "skipGroundPositioning" parameter is not critical then it may be possible to omit it and allow full KSP 1.3-1.7 compatibility.

**Comment by siimav** [comment]
@PhineasFreak that's true - I'm quite sure that it would work correctly from 1.3 all the way to 1.7. Do you think supporting 1.3.x would be useful?

**Comment by PhineasFreak** [comment]
That depends. If RP gets another KSP 1.3.1 release then it should be supported, otherwise there is no reason.

**Comment by siimav** [comment]
A traditional CKAN release looks a bit unlikely because of all the backports and forks that are needed to set that up. If RP-1 does get an official update for 1.3.1 then I think @pap1723 intends to do that in the modpack form in which case we could manually build a different version of KJR to make it compatible with 1.3.1.

**Comment by pap1723** [comment]
@PhineasFreak yeah, I looked into it a little, while I don't know if that parameter is entirely crucial, it VERY much helps to stabilize and stop the "jumping" craft on reload. We are going to have to play a lot of games to get a good release for 1.3.1 again, so we will add this to the list of things to change.

**Pull request merged**
